### ISSUE TITLE
Add Python 3 support

### ISSUE THREAD

**Issue by svisser** [bitmazk/django-development-fabfile#1]
Various commands are hardcoded to run `python2.7` which prevents this project from being used by users of Django 1.5+ on Python 3. It may also be good to clarify supported Python versions in `setup.py` and the `README`.

**Comment by Tyrdall** [comment]
@svisser Since we are not using Python 3 a pull request will be highly appreciated.
Nevertheless we will try to migrate all our apps to Python 3 in the future.

**Comment by Tyrdall** [comment]
Fixed in 2.14.5
